### ISSUE TITLE
OSError: Operation aborted with gopro MAX

### ISSUE THREAD

**Issue by scottEpicWin** [KonradIT/gopro-ble-py#19]
i am trying to control a gopro max from a windows 10 desktop.

I am running python3.10.11 with the following pip packages:
bleak== 0.15.1
bleak-winrt==1.2.0
goprocam== 4.2.0
termcolor== 2.3.0
prettytable== 3.8.0

the gopro is freshly factory reset and paired to the PC.

when i run main.py i get the following output:
```
D:\joe\code\gopro\gopro-ble-py>python3.10 main.py
Connecting to E1:30:E4:3D:20:32
+------+-------+
| Info | Value |
+------+-------+
+------+-------+
Traceback (most recent call last):
  File "D:\joe\code\gopro\gopro-ble-py\main.py", line 503, in <module>
    loop.run_until_complete(tasks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\joe\code\gopro\gopro-ble-py\main.py", line 355, in run
    await client.start_notify(commands.Characteristics.CommandNotifications, callback)
  File "C:\Users\VR-Labbie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bleak\backends\winrt\client.py", line 767, in start_notify
    await characteristic_obj.write_client_characteristic_configuration_descriptor_async(
OSError: [WinError -2147467260] Operation aborted
```

**Comment by scottEpicWin** [comment]
i just tried this on my ubuntu 18.04 laptop with the same python version and packages and it works as intended. 
it would still be nice to do this on windows, though.
